POST http://localhost:3333/users HTTP/1.1
Content-Type: application/json

{
     "name": "suport",
     "email": "suport@homecare.com.br",
     "password": "123456"
}

###
DELETE http://localhost:3333/users/63b6baba88e76428f8d0c68d HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3333/users HTTP/1.1
Content-Type: application/json


###
PUT http://localhost:3333/users/63c8a3f70d04ec442497bd91 HTTP/1.1
Content-Type: application/json

{
     "name": "suporte",
     "email": "suport@homecare.com.br"
}


###
POST http://localhost:3333/professional HTTP/1.1
Content-Type: application/json

{
    "fullName": "Novo usuário",
    "email": "teste@email.com.br",
    "mobile": "+55 (11) 91111-1111",
    "cpf": "114.222.222.01",
    "boardNumber": "565898/125",
    "regionZoneCode": 2,
    "address": {
          "logradouro": "Rua Doutor Araujo Castro",
          "number": "60",
          "city": "São Paulo",
          "uf": "SP",
          "postalCode": "02649-010",
          "complement": "Casa 3"
    }, 
    "bankAccount": [{
          "accountNumber": "0715372-4",
          "agencyNumber": "0545",
          "bankCode": "137",
          "accountType": 1
    }],
    "specialty": [{
     "description": "Enfermeiro"
    }]
}

###
GET http://localhost:3333/cep/02331003 HTTP/1.1
Content-Type: application/json
###
GET http://localhost:3333/cnpj/07961412000137 HTTP/1.1
Content-Type: application/json
###